<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statement [
  <!ELEMENT statement (select|update|insert|delete)>
  <!ELEMENT select (scan_columns,columns,parameters,tablescans,querycondition?,havingcondition?,ordercolumns?)>
  <!ATTLIST select
    limit CDATA #IMPLIED
    limit_paramid CDATA #IMPLIED
    offset CDATA #IMPLIED
    offset_paramid CDATA #IMPLIED
    distinct CDATA #IMPLIED
    grouped CDATA #IMPLIED
    aggregated CDATA #IMPLIED>
  <!ELEMENT values (columnref*|(value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT scan_columns (columnref*|column*|(value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT columns (columnref*|column*|(value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT parameters (parameter*)>
  <!ELEMENT parameter ANY>
  <!ATTLIST parameter
    index CDATA #REQUIRED
    id CDATA #REQUIRED
    type CDATA #REQUIRED>
  <!ELEMENT tablescans (tablescan*)>
  <!ELEMENT tablescan (searchkey?,startexp?,endexp?,postexp?)>
  <!ATTLIST tablescan
    type CDATA #REQUIRED
    table CDATA #REQUIRED
    index CDATA #IMPLIED
    alias CDATA #IMPLIED>
  <!ELEMENT searchkey ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT startexp ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT endexp ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT postexp ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT querycondition ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT havingcondition ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT value ANY>
  <!ATTLIST value
    id CDATA #REQUIRED
    type CDATA #REQUIRED
    value CDATA #IMPLIED
    isparam CDATA #IMPLIED>
  <!ELEMENT columnref ANY>
  <!ATTLIST columnref
    id CDATA #REQUIRED
    table CDATA #REQUIRED
    column CDATA #REQUIRED
    alias CDATA #IMPLIED
    dir CDATA #IMPLIED>
  <!ELEMENT bool ANY>
  <!ATTLIST bool
    id CDATA #REQUIRED
    value CDATA #REQUIRED>
  <!ELEMENT asterisk ANY>
  <!ELEMENT groupcolumns ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT ordercolumns ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT operation ((value|columnref|bool|asterisk|operation|function)*)>
  <!ATTLIST operation
    id CDATA #REQUIRED
    type CDATA #REQUIRED
    alias CDATA #IMPLIED
    distinct CDATA #IMPLIED
    desc CDATA #IMPLIED>
  <!ELEMENT function ((value|columnref|bool|asterisk|operation|function)*)>
  <!ATTLIST function
    id CDATA #IMPLIED
    name CDATA #REQUIRED
    type CDATA #REQUIRED>
  <!ELEMENT update (columns,parameters,tablescan,condition?)>
  <!ATTLIST update
    table CDATA #REQUIRED>
  <!ELEMENT condition ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT column ((value|columnref|bool|asterisk|operation|function)*)>
  <!ATTLIST column
    name CDATA #REQUIRED
    table CDATA #REQUIRED>
  <!ELEMENT insert (columns,parameters,tablescan?,condition?)>
  <!ATTLIST insert
    table CDATA #REQUIRED>
  <!ELEMENT delete (parameters,tablescan?,condition?)>
  <!ATTLIST delete
    table CDATA #REQUIRED>
]>
<statement>
    <insert table="CUSTOMER">
        <columns>
            <column table="CUSTOMER" name="C_ID">
                <value id="920482395" type="INTEGER" isparam="true" />
            </column>
            <column table="CUSTOMER" name="C_D_ID">
                <value id="75419777" type="TINYINT" isparam="true" />
            </column>
            <column table="CUSTOMER" name="C_W_ID">
                <value id="564840309" type="SMALLINT" isparam="true" />
            </column>
            <column table="CUSTOMER" name="C_FIRST">
                <value id="1393353623" type="VARCHAR" isparam="true" />
            </column>
            <column table="CUSTOMER" name="C_MIDDLE">
                <value id="1932654873" type="VARCHAR" isparam="true" />
            </column>
            <column table="CUSTOMER" name="C_LAST">
                <value id="1440289636" type="VARCHAR" isparam="true" />
            </column>
            <column table="CUSTOMER" name="C_STREET_1">
                <value id="512243268" type="VARCHAR" isparam="true" />
            </column>
            <column table="CUSTOMER" name="C_STREET_2">
                <value id="10664453" type="VARCHAR" isparam="true" />
            </column>
            <column table="CUSTOMER" name="C_CITY">
                <value id="996318870" type="VARCHAR" isparam="true" />
            </column>
            <column table="CUSTOMER" name="C_STATE">
                <value id="1201252431" type="VARCHAR" isparam="true" />
            </column>
            <column table="CUSTOMER" name="C_ZIP">
                <value id="955842370" type="VARCHAR" isparam="true" />
            </column>
            <column table="CUSTOMER" name="C_PHONE">
                <value id="1665033030" type="VARCHAR" isparam="true" />
            </column>
            <column table="CUSTOMER" name="C_SINCE">
                <value id="350731153" type="TIMESTAMP" isparam="true" />
            </column>
            <column table="CUSTOMER" name="C_CREDIT">
                <value id="2043361103" type="VARCHAR" isparam="true" />
            </column>
            <column table="CUSTOMER" name="C_CREDIT_LIM">
                <value id="211575297" type="FLOAT" isparam="true" />
            </column>
            <column table="CUSTOMER" name="C_DISCOUNT">
                <value id="1860580894" type="FLOAT" isparam="true" />
            </column>
            <column table="CUSTOMER" name="C_BALANCE">
                <value id="1273701491" type="FLOAT" isparam="true" />
            </column>
            <column table="CUSTOMER" name="C_YTD_PAYMENT">
                <value id="983965941" type="FLOAT" isparam="true" />
            </column>
            <column table="CUSTOMER" name="C_PAYMENT_CNT">
                <value id="1891488487" type="INTEGER" isparam="true" />
            </column>
            <column table="CUSTOMER" name="C_DELIVERY_CNT">
                <value id="1046574468" type="INTEGER" isparam="true" />
            </column>
            <column table="CUSTOMER" name="C_DATA">
                <value id="1886014746" type="VARCHAR" isparam="true" />
            </column>
        </columns>
        <parameters>
            <parameter index='0' id='920482395' type='INTEGER' />
            <parameter index='1' id='75419777' type='TINYINT' />
            <parameter index='2' id='564840309' type='SMALLINT' />
            <parameter index='3' id='1393353623' type='VARCHAR' />
            <parameter index='4' id='1932654873' type='VARCHAR' />
            <parameter index='5' id='1440289636' type='VARCHAR' />
            <parameter index='6' id='512243268' type='VARCHAR' />
            <parameter index='7' id='10664453' type='VARCHAR' />
            <parameter index='8' id='996318870' type='VARCHAR' />
            <parameter index='9' id='1201252431' type='VARCHAR' />
            <parameter index='10' id='955842370' type='VARCHAR' />
            <parameter index='11' id='1665033030' type='VARCHAR' />
            <parameter index='12' id='350731153' type='TIMESTAMP' />
            <parameter index='13' id='2043361103' type='VARCHAR' />
            <parameter index='14' id='211575297' type='FLOAT' />
            <parameter index='15' id='1860580894' type='FLOAT' />
            <parameter index='16' id='1273701491' type='FLOAT' />
            <parameter index='17' id='983965941' type='FLOAT' />
            <parameter index='18' id='1891488487' type='INTEGER' />
            <parameter index='19' id='1046574468' type='INTEGER' />
            <parameter index='20' id='1886014746' type='VARCHAR' />
        </parameters>
    </insert>
</statement>

