<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statement [
  <!ELEMENT statement (select|update|insert|delete)>
  <!ELEMENT select (scan_columns,columns,parameters,tablescans,querycondition?,havingcondition?,ordercolumns?)>
  <!ATTLIST select
    limit CDATA #IMPLIED
    limit_paramid CDATA #IMPLIED
    offset CDATA #IMPLIED
    offset_paramid CDATA #IMPLIED
    distinct CDATA #IMPLIED
    grouped CDATA #IMPLIED
    aggregated CDATA #IMPLIED>
  <!ELEMENT values (columnref*|(value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT scan_columns (columnref*|column*|(value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT columns (columnref*|column*|(value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT parameters (parameter*)>
  <!ELEMENT parameter ANY>
  <!ATTLIST parameter
    index CDATA #REQUIRED
    id CDATA #REQUIRED
    type CDATA #REQUIRED>
  <!ELEMENT tablescans (tablescan*)>
  <!ELEMENT tablescan (searchkey?,startexp?,endexp?,postexp?)>
  <!ATTLIST tablescan
    type CDATA #REQUIRED
    table CDATA #REQUIRED
    index CDATA #IMPLIED
    alias CDATA #IMPLIED>
  <!ELEMENT searchkey ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT startexp ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT endexp ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT postexp ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT querycondition ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT havingcondition ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT value ANY>
  <!ATTLIST value
    id CDATA #REQUIRED
    type CDATA #REQUIRED
    value CDATA #IMPLIED
    isparam CDATA #IMPLIED>
  <!ELEMENT columnref ANY>
  <!ATTLIST columnref
    id CDATA #REQUIRED
    table CDATA #REQUIRED
    column CDATA #REQUIRED
    alias CDATA #IMPLIED
    dir CDATA #IMPLIED>
  <!ELEMENT bool ANY>
  <!ATTLIST bool
    id CDATA #REQUIRED
    value CDATA #REQUIRED>
  <!ELEMENT asterisk ANY>
  <!ELEMENT groupcolumns ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT ordercolumns ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT operation ((value|columnref|bool|asterisk|operation|function)*)>
  <!ATTLIST operation
    id CDATA #REQUIRED
    type CDATA #REQUIRED
    alias CDATA #IMPLIED
    distinct CDATA #IMPLIED
    desc CDATA #IMPLIED>
  <!ELEMENT function ((value|columnref|bool|asterisk|operation|function)*)>
  <!ATTLIST function
    id CDATA #IMPLIED
    name CDATA #REQUIRED
    type CDATA #REQUIRED>
  <!ELEMENT update (columns,parameters,tablescan,condition?)>
  <!ATTLIST update
    table CDATA #REQUIRED>
  <!ELEMENT condition ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT column ((value|columnref|bool|asterisk|operation|function)*)>
  <!ATTLIST column
    name CDATA #REQUIRED
    table CDATA #REQUIRED>
  <!ELEMENT insert (columns,parameters,tablescan?,condition?)>
  <!ATTLIST insert
    table CDATA #REQUIRED>
  <!ELEMENT delete (parameters,tablescan?,condition?)>
  <!ATTLIST delete
    table CDATA #REQUIRED>
]>
<statement>
    <select>
        <scan_columns>
            <columnref id="657819519" table="CUSTOMER" column="C_ID" alias="C_ID" />
            <columnref id="726841077" table="CUSTOMER" column="C_D_ID" alias="C_D_ID" />
            <columnref id="1130997003" table="CUSTOMER" column="C_W_ID" alias="C_W_ID" />
            <columnref id="1288869824" table="CUSTOMER" column="C_FIRST" alias="C_FIRST" />
            <columnref id="367584679" table="CUSTOMER" column="C_MIDDLE" alias="C_MIDDLE" />
            <columnref id="1832731181" table="CUSTOMER" column="C_LAST" alias="C_LAST" />
            <columnref id="1355010146" table="CUSTOMER" column="C_STREET_1" alias="C_STREET_1" />
            <columnref id="1738931034" table="CUSTOMER" column="C_STREET_2" alias="C_STREET_2" />
            <columnref id="1108936415" table="CUSTOMER" column="C_CITY" alias="C_CITY" />
            <columnref id="2031238239" table="CUSTOMER" column="C_STATE" alias="C_STATE" />
            <columnref id="473546514" table="CUSTOMER" column="C_ZIP" alias="C_ZIP" />
            <columnref id="321865016" table="CUSTOMER" column="C_PHONE" alias="C_PHONE" />
            <columnref id="74017119" table="CUSTOMER" column="C_SINCE" alias="C_SINCE" />
            <columnref id="612687420" table="CUSTOMER" column="C_CREDIT" alias="C_CREDIT" />
            <columnref id="253380575" table="CUSTOMER" column="C_CREDIT_LIM" alias="C_CREDIT_LIM" />
            <columnref id="107252024" table="CUSTOMER" column="C_DISCOUNT" alias="C_DISCOUNT" />
            <columnref id="845987535" table="CUSTOMER" column="C_BALANCE" alias="C_BALANCE" />
            <columnref id="23273958" table="CUSTOMER" column="C_YTD_PAYMENT" alias="C_YTD_PAYMENT" />
            <columnref id="323388352" table="CUSTOMER" column="C_PAYMENT_CNT" alias="C_PAYMENT_CNT" />
            <columnref id="2054405154" table="CUSTOMER" column="C_DELIVERY_CNT" alias="C_DELIVERY_CNT" />
            <columnref id="1145346812" table="CUSTOMER" column="C_DATA" alias="C_DATA" />
        </scan_columns>
        <columns>
            <columnref id="657819519" table="CUSTOMER" column="C_ID" alias="C_ID" />
            <columnref id="726841077" table="CUSTOMER" column="C_D_ID" alias="C_D_ID" />
            <columnref id="1130997003" table="CUSTOMER" column="C_W_ID" alias="C_W_ID" />
            <columnref id="1288869824" table="CUSTOMER" column="C_FIRST" alias="C_FIRST" />
            <columnref id="367584679" table="CUSTOMER" column="C_MIDDLE" alias="C_MIDDLE" />
            <columnref id="1832731181" table="CUSTOMER" column="C_LAST" alias="C_LAST" />
            <columnref id="1355010146" table="CUSTOMER" column="C_STREET_1" alias="C_STREET_1" />
            <columnref id="1738931034" table="CUSTOMER" column="C_STREET_2" alias="C_STREET_2" />
            <columnref id="1108936415" table="CUSTOMER" column="C_CITY" alias="C_CITY" />
            <columnref id="2031238239" table="CUSTOMER" column="C_STATE" alias="C_STATE" />
            <columnref id="473546514" table="CUSTOMER" column="C_ZIP" alias="C_ZIP" />
            <columnref id="321865016" table="CUSTOMER" column="C_PHONE" alias="C_PHONE" />
            <columnref id="74017119" table="CUSTOMER" column="C_SINCE" alias="C_SINCE" />
            <columnref id="612687420" table="CUSTOMER" column="C_CREDIT" alias="C_CREDIT" />
            <columnref id="253380575" table="CUSTOMER" column="C_CREDIT_LIM" alias="C_CREDIT_LIM" />
            <columnref id="107252024" table="CUSTOMER" column="C_DISCOUNT" alias="C_DISCOUNT" />
            <columnref id="845987535" table="CUSTOMER" column="C_BALANCE" alias="C_BALANCE" />
            <columnref id="23273958" table="CUSTOMER" column="C_YTD_PAYMENT" alias="C_YTD_PAYMENT" />
            <columnref id="323388352" table="CUSTOMER" column="C_PAYMENT_CNT" alias="C_PAYMENT_CNT" />
            <columnref id="2054405154" table="CUSTOMER" column="C_DELIVERY_CNT" alias="C_DELIVERY_CNT" />
            <columnref id="1145346812" table="CUSTOMER" column="C_DATA" alias="C_DATA" />
        </columns>
        <parameters>
            <parameter index='0' id='1947941223' type='TINYINT' />
            <parameter index='1' id='659936446' type='INTEGER' />
            <parameter index='2' id='1946294814' type='SMALLINT' />
        </parameters>
        <tablescans>
            <tablescan type="sequential" table="CUSTOMER">
                <postexp>
                    <operation id="-379760938" type="and">
                        <operation id="2069845375" type="and">
                            <operation id="-700808754" type="and">
                                <operation id="-1611626919" type="and">
                                    <operation id="535009734" type="and">
                                        <operation id="-1672924588" type="equal">
                                            <columnref id="906027794" table="CUSTOMER" column="C_W_ID" alias="C_W_ID" />
                                            <value id="1946294814" type="SMALLINT" isparam="true" />
                                        </operation>
                                        <operation id="1171141047" type="equal">
                                            <columnref id="1950076528" table="CUSTOMER" column="C_D_ID" alias="C_D_ID" />
                                            <value id="1947941223" type="TINYINT" isparam="true" />
                                        </operation>
                                    </operation>
                                    <operation id="-1723429347" type="equal">
                                        <columnref id="40785582" table="CUSTOMER" column="C_ID" alias="C_ID" />
                                        <value id="659936446" type="INTEGER" isparam="true" />
                                    </operation>
                                </operation>
                                <operation id="-1672924588" type="equal">
                                    <columnref id="906027794" table="CUSTOMER" column="C_W_ID" alias="C_W_ID" />
                                    <value id="1946294814" type="SMALLINT" isparam="true" />
                                </operation>
                            </operation>
                            <operation id="1171141047" type="equal">
                                <columnref id="1950076528" table="CUSTOMER" column="C_D_ID" alias="C_D_ID" />
                                <value id="1947941223" type="TINYINT" isparam="true" />
                            </operation>
                        </operation>
                        <operation id="-1723429347" type="equal">
                            <columnref id="40785582" table="CUSTOMER" column="C_ID" alias="C_ID" />
                            <value id="659936446" type="INTEGER" isparam="true" />
                        </operation>
                    </operation>
                </postexp>
            </tablescan>
        </tablescans>
        <querycondition>
            <operation id="-1302778275" type="and">
                <operation id="1873780688" type="and">
                    <operation id="1171141047" type="equal">
                        <columnref id="1950076528" table="CUSTOMER" column="C_D_ID" alias="C_D_ID" />
                        <value id="1947941223" type="TINYINT" isparam="true" />
                    </operation>
                    <operation id="-1723429347" type="equal">
                        <columnref id="40785582" table="CUSTOMER" column="C_ID" alias="C_ID" />
                        <value id="659936446" type="INTEGER" isparam="true" />
                    </operation>
                </operation>
                <operation id="-1672924588" type="equal">
                    <columnref id="906027794" table="CUSTOMER" column="C_W_ID" alias="C_W_ID" />
                    <value id="1946294814" type="SMALLINT" isparam="true" />
                </operation>
            </operation>
        </querycondition>
    </select>
</statement>

