<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE statement [
  <!ELEMENT statement (select|update|insert|delete)>
  <!ELEMENT select (scan_columns,columns,parameters,tablescans,querycondition?,havingcondition?,ordercolumns?)>
  <!ATTLIST select
    limit CDATA #IMPLIED
    limit_paramid CDATA #IMPLIED
    offset CDATA #IMPLIED
    offset_paramid CDATA #IMPLIED
    distinct CDATA #IMPLIED
    grouped CDATA #IMPLIED
    aggregated CDATA #IMPLIED>
  <!ELEMENT values (columnref*|(value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT scan_columns (columnref*|column*|(value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT columns (columnref*|column*|(value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT parameters (parameter*)>
  <!ELEMENT parameter ANY>
  <!ATTLIST parameter
    index CDATA #REQUIRED
    id CDATA #REQUIRED
    type CDATA #REQUIRED>
  <!ELEMENT tablescans (tablescan*)>
  <!ELEMENT tablescan (searchkey?,startexp?,endexp?,postexp?)>
  <!ATTLIST tablescan
    type CDATA #REQUIRED
    table CDATA #REQUIRED
    index CDATA #IMPLIED
    alias CDATA #IMPLIED>
  <!ELEMENT searchkey ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT startexp ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT endexp ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT postexp ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT querycondition ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT havingcondition ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT value ANY>
  <!ATTLIST value
    id CDATA #REQUIRED
    type CDATA #REQUIRED
    value CDATA #IMPLIED
    isparam CDATA #IMPLIED>
  <!ELEMENT columnref ANY>
  <!ATTLIST columnref
    id CDATA #REQUIRED
    table CDATA #REQUIRED
    column CDATA #REQUIRED
    alias CDATA #IMPLIED
    dir CDATA #IMPLIED>
  <!ELEMENT bool ANY>
  <!ATTLIST bool
    id CDATA #REQUIRED
    value CDATA #REQUIRED>
  <!ELEMENT asterisk ANY>
  <!ELEMENT groupcolumns ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT ordercolumns ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT operation ((value|columnref|bool|asterisk|operation|function)*)>
  <!ATTLIST operation
    id CDATA #REQUIRED
    type CDATA #REQUIRED
    alias CDATA #IMPLIED
    distinct CDATA #IMPLIED
    desc CDATA #IMPLIED>
  <!ELEMENT function ((value|columnref|bool|asterisk|operation|function)*)>
  <!ATTLIST function
    id CDATA #IMPLIED
    name CDATA #REQUIRED
    type CDATA #REQUIRED>
  <!ELEMENT update (columns,parameters,tablescan,condition?)>
  <!ATTLIST update
    table CDATA #REQUIRED>
  <!ELEMENT condition ((value|columnref|bool|asterisk|operation|function)*)>
  <!ELEMENT column ((value|columnref|bool|asterisk|operation|function)*)>
  <!ATTLIST column
    name CDATA #REQUIRED
    table CDATA #REQUIRED>
  <!ELEMENT insert (columns,parameters,tablescan?,condition?)>
  <!ATTLIST insert
    table CDATA #REQUIRED>
  <!ELEMENT delete (parameters,tablescan?,condition?)>
  <!ATTLIST delete
    table CDATA #REQUIRED>
]>
<statement>
    <update table="CUSTOMER">
        <columns>
            <column table="CUSTOMER" name="C_BALANCE">
                <operation id="-1941791277" type="add">
                    <columnref id="544589709" table="CUSTOMER" column="C_BALANCE" alias="C_BALANCE" />
                    <value id="343935649" type="FLOAT" isparam="true" />
                </operation>
            </column>
        </columns>
        <parameters>
            <parameter index='0' id='343935649' type='FLOAT' />
            <parameter index='1' id='1647958666' type='INTEGER' />
            <parameter index='2' id='1144704103' type='TINYINT' />
            <parameter index='3' id='1883349295' type='SMALLINT' />
        </parameters>
        <tablescan type="sequential" table="CUSTOMER">
            <postexp>
                <operation id="432779501" type="and">
                    <operation id="-1388983660" type="and">
                        <operation id="1661771670" type="equal">
                            <columnref id="1690127932" table="CUSTOMER" column="C_W_ID" alias="C_W_ID" />
                            <value id="1883349295" type="SMALLINT" isparam="true" />
                        </operation>
                        <operation id="1156636790" type="equal">
                            <columnref id="1213954255" table="CUSTOMER" column="C_D_ID" alias="C_D_ID" />
                            <value id="1144704103" type="TINYINT" isparam="true" />
                        </operation>
                    </operation>
                    <operation id="1198580286" type="equal">
                        <columnref id="1834517285" table="CUSTOMER" column="C_ID" alias="C_ID" />
                        <value id="1647958666" type="INTEGER" isparam="true" />
                    </operation>
                </operation>
            </postexp>
        </tablescan>
        <condition>
            <operation id="432779501" type="and">
                <operation id="-1388983660" type="and">
                    <operation id="1661771670" type="equal">
                        <columnref id="1690127932" table="CUSTOMER" column="C_W_ID" alias="C_W_ID" />
                        <value id="1883349295" type="SMALLINT" isparam="true" />
                    </operation>
                    <operation id="1156636790" type="equal">
                        <columnref id="1213954255" table="CUSTOMER" column="C_D_ID" alias="C_D_ID" />
                        <value id="1144704103" type="TINYINT" isparam="true" />
                    </operation>
                </operation>
                <operation id="1198580286" type="equal">
                    <columnref id="1834517285" table="CUSTOMER" column="C_ID" alias="C_ID" />
                    <value id="1647958666" type="INTEGER" isparam="true" />
                </operation>
            </operation>
        </condition>
    </update>
</statement>

